dist: xenial
language: cpp

addons:
  apt:
    packages:
      - cmake
      - build-essential
      - cppcheck
      - git
      - make
      - binutils-dev
      - libiberty-dev
      - openssl
      - libssl-dev
      - zlib1g-dev

git:
  depth: 1

before_install:
  - sudo apt-get -qq install mariadb-server libace-6.* libace-dev
  - if [[ $TRAVIS_PULL_REQUEST == 'true' ]]; then exit; fi

matrix:
  include:
    - os: linux
      arch: amd64
      name: "Eluna Disabled clang x64"
      compiler: clang
      env:
        - CC=clang
        - CXX=clang++
      install:
        - mkdir build
        - mkdir _install
        - cd build
        - cmake .. -DCMAKE_INSTALL_PREFIX=../_install -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DSERVERS=1 -DTOOLS=1 -DSCRIPTS=1 -DWITH_DOCS=1 -DWITH_WARNINGS=0 -DELUNA=0 -DWITH_COREDEBUG=0
        - make -j4
        - make install

script:
  - cd $TRAVIS_BUILD_DIR/sql
  - sudo mysql -u root --password='' < create/create_mysql.sql
  - mysql -u oregon -poregon realmd < base/realmd.sql
  - mysql -u oregon -poregon characters < base/characters.sql
  - mysql -u oregon -poregon world < base/world.sql
  - cat updates/realmd/*.sql | mysql -u oregon -poregon realmd
  - cat updates/characters/*.sql | mysql -u oregon -poregon characters
  - cat updates/world/*.sql | mysql -u oregon -poregon world
